from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(755, 484)
        self.FetchStatics = QtWidgets.QPushButton(Dialog)
        self.FetchStatics.setGeometry(QtCore.QRect(60, 170, 541, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.FetchStatics.setFont(font)
        self.FetchStatics.setMouseTracking(False)
        self.FetchStatics.setAutoFillBackground(False)
        self.FetchStatics.setIconSize(QtCore.QSize(20, 20))
        self.FetchStatics.setFlat(False)
        self.FetchStatics.setObjectName("FetchStatics")
        self.keoword = QtWidgets.QLineEdit(Dialog)
        self.keoword.setGeometry(QtCore.QRect(60, 70, 281, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.keoword.setFont(font)
        self.keoword.setAutoFillBackground(False)
        self.keoword.setStyleSheet("")
        self.keoword.setInputMethodHints(QtCore.Qt.ImhNone)
        self.keoword.setInputMask("")
        self.keoword.setPlaceholderText("")
        self.keoword.setObjectName("keoword")
        self.lineEdit_2 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_2.setGeometry(QtCore.QRect(450, 70, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.search_label = QtWidgets.QLabel(Dialog)
        self.search_label.setGeometry(QtCore.QRect(60, 29, 281, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.search_label.setFont(font)
        self.search_label.setAutoFillBackground(True)
        self.search_label.setFrameShape(QtWidgets.QFrame.Panel)
        self.search_label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.search_label.setTextFormat(QtCore.Qt.AutoText)
        self.search_label.setScaledContents(False)
        self.search_label.setWordWrap(False)
        self.search_label.setObjectName("search_label")
        self.number_label = QtWidgets.QLabel(Dialog)
        self.number_label.setGeometry(QtCore.QRect(450, 20, 151, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.number_label.setFont(font)
        self.number_label.setFrameShape(QtWidgets.QFrame.Panel)
        self.number_label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.number_label.setLineWidth(1)
        self.number_label.setMidLineWidth(0)
        self.number_label.setObjectName("number_label")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.FetchStatics.setText(_translate("Dialog", "Fetch Statics"))
        self.keoword.setText(_translate("Dialog", "e.g: python learning"))
        self.lineEdit_2.setText(_translate("Dialog", "100"))
        self.search_label.setText(_translate("Dialog", "Keyword Search"))
        self.number_label.setText(_translate("Dialog", "Videos Number"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
